### ISSUE TITLE
gdal2kml.py transform((x,y)) invalid syntax

### ISSUE THREAD

**Issue by jamierob** [tf198/gdal2custommap#2]
Hello - I realize this is a very old project, so likely sunsetted, but it is the best thing I've seen for the possibility of getting a custom raster map onto older garmin devices. (I've had no luck with google earth pro .kmz creation)

When I run the gdal2kml.py script I get: 

# python3 gdal2kml.py Niokolo_Z3_Final_4326.tif output.kml --crop 20
  File "/usr/lib/img_garmin_test/gdal2kml.py", line 52
    def transform((x, y)):
                           ^
SyntaxError: invalid syntax

I've tried to sort it out, but alas my python skills are lacking. and help would be greatly appreciated if you are still monitoring this repo. I'm on Ubuntu 22.04.2

**Comment by kogens** [comment]
Hi @jamierob , the original scripts were written for Python2 and wont work with Python3. I'm keeping a Python 3 fork here if you still need it: https://github.com/kogens/gdal2custommap

**Comment by jamierob** [comment]
python2! Thank you.
